FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3

# Install requirements only first to cache
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt && rm /tmp/*

WORKDIR /hass
COPY ./src ./

# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1

ENTRYPOINT ["/hass/entrypoint.sh"]