FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt && rm /tmp/*

WORKDIR /hass
COPY . ./

# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1

CMD ["sh", "-c", "modprobe w1-gpio && modprobe w1-therm python -u component.py"]